### ISSUE TITLE
Mix & Match configuration

### ISSUE THREAD

**Issue by fabi1cazenave** [OneDeadKey/arsenik#11]
We’ve started with a one-size-fits-all approach, and I now think it’s a mistake.

The [Atomic mod](https://github.com/OneDeadKey/arsenik/tree/main/mods/atomic) looks like a much saner approach : every feature is in its own `kbd` file, which makes it easy to customize and extend. It currently allows : 
- both ESDF {Arsenik) and HJKL (Selenium) navigation modes
- PC and Mac shortcuts and thumb keys
- various keyboard layouts
- angle mods !

This should become the default Arsenik implementation, with some documentation to explain (with SVG visuals) how to customize it.

**Comment by trilowy** [comment]
Now that #26 is merged and we have the documentation on how to customize, I think we can safely close this issue.
