### ISSUE TITLE
No numpad in arsenik nav layer

### ISSUE THREAD

**Issue by GFNIAE** [OneDeadKey/arsenik#17]
Hello,

Thanks for this nice approach to ergonomics on a normal keyboard !

I tried arsenik through kanaka.
I use my laptop keyboard, ISO, with a bépo layout at the moment.
I use arsenik_easy_altgr.kbd as a config file.
I followed the procedure not to have to call sudo.

It seems to work, which is great !

But strangely enough, in nav layer : 
All the left part is as described for left, right, home, pageend…
But ctlr-A works, and ctlr-Z does not. Not sure for others.
And the right part gives symbols instead of numpad. Is that expected on a bépo layout ?

**Comment by trilowy** [comment]
Hello GFNIAE, we’ve reworked arsenik to take into account different layouts, including Bépo. It should fix your issue with the shortcuts, if it doesn’t, please let us know, I’ll reopen the issue.
