### ISSUE TITLE
Delay in space bar

### ISSUE THREAD

**Issue by GFNIAE** [OneDeadKey/arsenik#18]
I just installed arsenik through kanaka on linux (cf my last message about missing numpad)

I can feel a slight delay for my laptop to react to the space bar, and that’s not nice when using it as space (normal, quick strokes). To write text feels sluggish.

Is there a way to make it snappier, especially for the space bar ?

**Comment by Nuclear-Squid** [comment]
Hi ! Sadly not, the software needs to know if we held the key or tapped it before sending the signal. This means the space key is only sent when the key is *released* not pressed (like for other keys). This behavior is shared accros *all* of the mod-taps or layer-taps, and there is sadly nothing we can do about it. Though if it reassures you, it does not slow down your tying (you can still press the keys at the same speed), and is barely noticeable once you get used to it.

**Comment by trilowy** [comment]
I hope Nuclear-Squid has answered your question, I’m closing the issue but feel free to reopen it if not.
