### ISSUE TITLE
Change default enabled feature

### ISSUE THREAD

**Issue by trilowy** [OneDeadKey/arsenik#27]
As @fabi1cazenave said: maybe the angle mod should not be enabled by default, e.g. if we consider how many could be using ANSI keyboards.

**Comment by cypriani** [comment]
Je dirais même plus : ANSI or orthogonal keyboards (i.e. non-ISO).

**Comment by bouttier** [comment]
Another argument: if you want anglemod, you may already have enabled it through kalamine `--angle-mod` (which is ihmo a preferable option than kanata, in order to have the same keymap in grub and when typing luks password, and to keep kanata for fancy features like lt & hrm).
