### ISSUE TITLE
[kanata] 5 & 6 not working on num layer when AltGr is kept depressed

### ISSUE THREAD

**Issue by cypriani** [OneDeadKey/arsenik#29]
On the numeric layer (AltGr + Alt), 5 and 6 cannot be typed and when attempted, they "block" further input. For instance, if I attempt to type "123454", I get "1234". After some more testing, I realize this seems to happen only when I keep AltGr depressed after activating the num layer with Alt.

See [debug trace](https://github.com/user-attachments/files/16854575/123454.log) and [kanata.kbd](https://github.com/user-attachments/files/16855023/kanata.kbd.txt).

Something I noted that may or may not be related: the last layer printed in the terminal (upon pressing the final "4") is the same as the one that appears when pressing Alt *then* AltGr (rather than AltGr then Alt), which also blocks any input:

```
(deflayer symbols
  AG-1 AG-2 AG-3 AG-4 AG-5  XX  AG-6 AG-7 AG-8 AG-9 AG-0
  AG-q AG-w AG-e AG-r AG-t      AG-y AG-u AG-i AG-o AG-p
  AG-a AG-s AG-d AG-f AG-g      AG-h AG-j AG-k AG-l AG-;
  AG-z AG-x AG-c AG-v AG-b  XX  AG-n AG-m AG-, AG-. AG-/
            @num           spc            _
)
```

Environment:
- OS : Debian sid
- DE : KDE Plasma
- Keymap: fr ergol
- Kanata 1.6.1 running as root from the CLI

**Comment by Nuclear-Squid** [comment]
hmm, this sounds like a [ghosting](https://en.wikipedia.org/wiki/Key_rollover#Ghosting) issue to me. Are you on a membrane keyboard ? Does the issue persist when kanata *isn’t* active ? I have a similar problem with my keyboard (though only on Alt + AltGr + 5, surprisingly) and the [keyboard testing](https://config.qmk.fm/#/test) feature of QMK configurator shows a very similar problem.

**Comment by cypriani** [comment]
That’s it. I’m typing on a TypeMatrix (so yes, membrane) connected to my laptop, and yes the problem exists without Kanata. And the laptop’s integrated keyboard doesn’t have the issue.

Good catch, thanks!
