### ISSUE TITLE
[BUG] long_hold_timeout in base_lt_hrm.kbd and duplicate variable definition

### ISSUE THREAD

**Issue by zenny** [OneDeadKey/arsenik#43]
Hi @Nuclear-Squid,

I pulled the latest (https://github.com/OneDeadKey/arsenik/commit/e82a4104d988261688ed59d7e3496acb6516a258) commit .

1. I enabled `base_lt_hrm.kbd`, but its states that 300 is a high timeout value and duplicate definition of a variable:

```
$ kanata -c arsenik/kanata/kanata.kbd
07:59:43.6582 [INFO] kanata v1.7.0-prerelease-1 starting
07:59:43.6588 [INFO] process unmapped keys: true
07:59:43.6589 [ERROR]   × Error in configuration
    ╭─[deflayer/base_lt_hrm.kbd:17:1]
 17 │   ;; Slightly higher value for tapying keys, to prevent unexpected hold effect.
 18 │   long_hold_timeout 300
    ·   ────────┬────────
    ·           ╰── Error here
 19 │ )
    ╰────
  help: duplicate variable name: long_hold_timeout

        For more info, see the configuration guide:
        https://github.com/jtroo/kanata/blob/main/docs/config.adoc

07:59:43.6590 [ERROR] failed to parse file


Press enter to exit
```

2. Nevertheless, it works fine with `base_lt.kbd`, fyi.
3. Yet pressing `z` in the navigation layer for `undo` crashes `kanata`:

```
08:08:02.5833 [INFO] Entered layer:

(deflayer navigation
  M-1  M-2  M-3  M-4  M-5  lrld M-6  M-7  M-8  M-9  M-0
  tab  home up   end  pgup      @/   @7   @8   @9   @run
  @all lft  down rght pgdn      @-   @4   @5   @6   @0
  @ndo @cut @cpy @pst S-tab _   @,   @1   @2   @3   @.
            del             _             esc
)
^X^Z08:08:05.3795 [ERROR] failed poll: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }
08:08:05.3795 [WARN] got SIGTSTP, exiting instead of pausing so keyboards don't hang
```

Cheers,
/zenny

**Comment by Nuclear-Squid** [comment]
Woops, I did the all time classic of “this such a simple change, there is absolutely no way this *doesn’t work ! \*crashes prod\*” move. I’ll look into it.

For your third point, did you press `undo` in the terminal that was running `kanata` ? If so that is that’s intended : it sends ctrl-z, which is the `stop` signal (which was caught by `kanata`, see last line : `[WARN] got SIGTSTP, exiting` ...)

**Comment by Nuclear-Squid** [comment]
I opened a PR (#44) that fixes the problems with the variables (and this time I checked ^^). I’ll merge it and close this issue once we have a final answer for problem n°3

**Comment by zenny** [comment]
> Woops, I did the all time classic of “this is such a simple change, there is absolutely no way this *doesn’t work ! *crashes prod*” move. I’ll look into it.
> 
> For your third point, did you press `undo` in the terminal that was running `kanata` ? If so that is that’s intended : it sends ctrl-z, which is the `stop` signal (which was caught by `kanata`, see last line : `[WARN] got SIGTSTP, exiting` ...)

About 3, yes I did that in terminal and reportedly `C-z` is assigned to signal `stop`. Thanks.
