### ISSUE TITLE
AZERTY-FR Keyboard Inputs Mapped as QWERTY in Symbols, Navigation, and NumRow Layers on Windows

### ISSUE THREAD

**Issue by babforlife** [OneDeadKey/arsenik#57]
Hello!

Thank you for this nice project. I use it through kanata on a Windows laptop.
I have an AZERTY-FR keyboard, and I can't get some of the symbols, navigation, and numRow layers to work correctly, as it seems to convert AZERTY inputs into QWERTY inputs.

For example, on the numRow layer to get a ```1``` I need to press ```a``` instead of ```q```.
Is there some configuration I am missing ?

Thank you in advance for your help!

Here is my kanata.kbd conf :
```
(defvar
  tap_timeout 200
  hold_timeout 200
  long_hold_timeout 300
)
(include defsrc/pc.kbd)  ;; PC, standard finger assignment
(include deflayer/base_lt.kbd)  ;; layer-taps on both thumb keys
(include deflayer/symbols_lafayette_num.kbd)  ;; AltGr prog layer + NumRow layers
(include deflayer/navigation_vim.kbd)  ;; HJKL + NumPad on [Space]+[Q]
(defalias run XX)  ;; do nothing
(include defalias/azerty_pc.kbd)  ;; Azerty PC
(defcfg
  process-unmapped-keys yes
  windows-altgr cancel-lctl-press
)
```

**Comment by fnuttens** [comment]
@babforlife glad to see you here! I believe that’s the kind of error that the experimental winiov2 mechanism fixes on Windows. You can take advantage from it either by installing the [base](https://github.com/jtroo/kanata/releases/download/v1.7.0/kanata_winIOv2.exe) or the [gui](https://github.com/jtroo/kanata/releases/download/v1.7.0/kanata_gui.exe) version.

**Comment by babforlife** [comment]
Thank you for the support @fnuttens, it works great with the version you provided. 
The issue is that I was using kanata with scoop.
