### ISSUE TITLE
text selection does not work as expected

### ISSUE THREAD

**Issue by Yvan-Masson** [OneDeadKey/arsenik#62]
Hi,
I am using arsenik 0.2.0 with kanata 1.7.0, on top of ergol layout.
I have enabled:
```
(include defsrc/pc_anglemod.kbd)  ;; PC, ZXCVB are shifted to the left
(include deflayer/base_lt_hrm.kbd)  ;; layer-taps + home-row mods
(include deflayer/symbols_noop.kbd)  ;; AltGr stays as-is
(include deflayer/navigation.kbd)  ;; ESDF on the left, NumPad on the right
(include defalias/ergol_pc.kbd)  ;; Ergo‑L PC
```

Everything seems to work except:
- when trying to do Ctrl (by maintaining T) + Left (by maintaining Space and pressing S), nothing happens because Left is not recognized. It works perfectly when doing Ctrl+Up/Down/Right
- when trying to do Ctrl+Shift+Begin/End, selection is done to the top / to the bottom: I would expect instead that selection goes to the start / to the end of the line

Any help would be greatly appreciated.

**Comment by Yvan-Masson** [comment]
After a night of sleep I realize that I was off the mark: I was doing Ctrl+Shift+Begin/End instead of simply Shift+Begin/End…

But the first issue remains: Ctrl+Left does not work. I made a few tests assisted by xev:

- it does not work when doing Ctrl by maintaining T (Ctrl_right)
- it does work when doing Ctrl by others means : by maintaining E (Ctrl_left) or physical Ctrl_Right or physical Ctrl_Left

**Comment by yvan-algoo** [comment]
I just tried with an external keyboard and it works perfectly, so I suppose this is an issue with my integrated keyboard and kanata…
