### ISSUE TITLE
Question: How to input the € (euro) sign on a compact keyboard ?

### ISSUE THREAD

**Issue by doc75** [OneDeadKey/arsenik#63]
I am starting to use Arsenik and I already activated angle-mod + layer-tap, but I still need to use the number row to enter the € sign.
I have not seen where it is located in the compact layout.

**Comment by fnuttens** [comment]
@doc75 enabling either of `deflayer/symbols_noop_num.kbd` or `deflayer/symbols_lafayette_num.kbd` symbols layer will also give you access to the [numrow](https://github.com/OneDeadKey/arsenik?tab=readme-ov-file#num-row--num-pad). € will then be accessible through `sym-num-[Q]`.

**Comment by doc75** [comment]
@fnuttens thanks a lot for the explanation. I guess that the picture for the [numrow](https://github.com/OneDeadKey/arsenik?tab=readme-ov-file#num-row--num-pad) is not up-to-date as it shows "!" instead of "€" (reason why I did not see it probably 😉)

**Comment by doc75** [comment]
Closed

**Comment by fnuttens** [comment]
> I guess that the picture for the [numrow](https://github.com/OneDeadKey/arsenik?tab=readme-ov-file#num-row--num-pad) is not up-to-date as it shows "!" instead of "€"

It shows `!` because that’s what `S-[1]` gives you on Qwerty, which is the universal layout used by Arsenik for documentation purposes.

**Comment by doc75** [comment]
> It shows `!` because that’s what `S-[1]` gives you on Qwerty, which is the universal layout used by Arsenik for documentation purposes.

Thanks @fnuttens  for the clarification. I am too much Ergol oriented 😂
